config/routes.rb
Rails.application.routes.draw do
  # get 'sales/index'
  # get 'sales/new'
  # get 'clients/index'
  # get 'clients/new'
  # get 'clients/show'
  # get 'clients/edit'
  # namespace :categories do
  #   get 'dishes/index'
  #   get 'dishes/new'
  #   get 'dishes/edit'
  #   get 'dishes/show'
  # end
  # resources :dishes
  # resources :categories
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :profiles
  resources :clients
  resources :sales
  resources :categories do
    resources :dishes, module: :categories
  end
  post '/search', to: 'search#results'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes, dependent: :destroy

    def self.buscador(termino)
      Category.where("nombre LIKE ?", "%#{termino}%")
    end

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
  validates :nombre, format: { with: /\A[a-z A-Z]+\z/, message: "debe incluir sólo letras" }
  validates_format_of :correo,{with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'debe ser válido!'}
  validates :direccion, presence: true
  validates :cedula, length: { in: 10..10 },numericality: true
  validates :telefono, length: { in: 10..10 },numericality: true

   def to_s
      self.nombre
     # "#{self.cedula} - #{self.nombre}"
   end

end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  def self.buscador(termino)
    Dish.where("nombre LIKE ?", "%#{termino}%")
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_details
  belongs_to :client
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :user_mailer
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :profile

         def user_mailer
           UserMailer.bienvenida_mailer(@user).deliver_later!
         end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    authorize Client
    @clients = Client.paginate(page: params[:page], per_page:4)
  end

  def new
    @clients = Client.new
    authorize @clients
  end

  def edit

  end

  def show
  end

  def create
    @clients = Client.new(client_params)

    respond_to do |format|
      if @clients.save
        format.html {redirect_to clients_url, notice: 'Cliente creado exitosamente'}
        format.json {render :show, status: :created, location: @clients}
      else
        format.html {render :new}
        format.json {reder json: @clients.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @clients.update (client_params)
        format.html {redirect_to clients_url, notice: 'El clientes se ha actualizado exitosamente'}
        format.json {reder :show, status: :ok, location: @clients}
      else
        format.html {render :edit}
        format.json {render json: @clients.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @clients.destroy
    respond_to do |format|
      format.html {redirect_to clients_url, notice: 'Cliente eliminado con éxito'}
      format.json { head :no_content}

    end
  end

  private

  def set_client
    @clients = Client.find(params[:id])

  end

  def client_params
    params.require(:client).permit(:nombre, :correo, :direccion, :cedula, :telefono, :estado)

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:edit, :destroy]

  def index
    @sales = Sale.paginate(page: params[:page], per_page:4)
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_url, notice: '  se ha creado'}

        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy
      respond_to do |format|
        format.html { redirect_to sales_url, notice: 'La venta ha sido cancelada.' }
        format.json { head :no_content }
    end
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:total, :client_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
def results
    @categories = Category.buscador(params[:termino])
    @dishes = Dish.buscador(params[:termino])
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/_dishes.html.erb
<div class="modal fade" id="buscador_plato" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-items-title">Buscador de platos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-items modal-body" id="modal-body-items">
        <div class="form-group">
            <label for="buscador">Ingresa el nombre del plato</label>
            <input type="text" class="form-control" data-tipo = "<%= @tipo %>" data-model = "<%= @model.try(:id) %>" id="buscador_plato" placeholder="Nombre plato...">
        </div>
        <div class="form-group">
            <label for="buscador">Ingresa una cantidad</label>
            <input type="number" class="form-control" id="cantidad_plato" placeholder="Ingresa la cantidad a vender..." value="1">
        </div>
        <table class="table" id="tabla_buscador" >
            <thead>
                <tr>
                  <th >Nombre</th>
                  <th >Existencia</th>
                  <th >Agregar</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
      </div>
      <div class="modal-footer" id="modal-footer-items">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/search/results.html.erb
<table id="tablaCategories" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <body>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.nombre %></td>
      <td><%= category.descripcion %></td>
      <%if current_user.has_role? :admin%>

      <td align="center"><%= link_to 'Editar', edit_category_path(category), class:"btn btn-info" %></td>
      <td align="center"><%= link_to 'Borrar', category, method: :delete, data: { confirm: "Desea borrar la categoria de #{category.nombre}?"}, class:"btn btn-danger" %></td>
      <td align="center"><%= link_to 'platos', category_dishes_path(category), class:"btn btn-success" %></td>
      <%else%>
        <td align="center"><%= link_to 'platos', category_dishes_path(category), class:"btn btn-success" %></td>
      <%end%>
    </tr>
    <% end %>
  </body>
</table>

<table id="tablaCategories" class="table table-bordered table-hover">
<thead>
<tr>
  <th>Nombre</th>
  <th>Existencia</th>
  <th>Precio</th>
  <th>Descripcion</th>
  <th>Categoria</th>
  <th>Descripcion</th>
  <th colspan="3"></th>
</tr>
</thead>

<body>
  <% @dishes.each do |dish| %>
      <tr>
       <td><%= dish.nombre %></td>
       <td><%= dish.existencia %></td>
       <td><%= dish.precio %></td>
       <td><%= dish.descripcion %></td>
       <td><%= dish.category.nombre %></td>
       <td><%= dish.category.descripcion %></td>

      </tr>
    <% end %>
</body>
</table>