config/routes.rb
Rails.application.routes.draw do
  # get 'sales/index'
  # get 'sales/new'
  # get 'clients/index'
  # get 'clients/new'
  # get 'clients/show'
  # get 'clients/edit'
  # namespace :categories do
  #   get 'dishes/index'
  #   get 'dishes/new'
  #   get 'dishes/edit'
  #   get 'dishes/show'
  # end
  # resources :dishes
  # resources :categories
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :profiles
  resources :clients
  resources :sales
  resources :categories do
    resources :dishes, module: :categories
  end
  post '/search', to: 'search#results'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
  validates :nombre, format: { with: /\A[a-z A-Z]+\z/, message: "debe incluir sólo letras" }
  validates_format_of :correo,{with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'debe ser válido!'}
  validates :direccion, presence: true
  validates :cedula, length: { in: 10..10 },numericality: true
  validates :telefono, length: { in: 10..10 },numericality: true

   def to_s
      self.nombre
     # "#{self.cedula} - #{self.nombre}"
   end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    authorize Client
    @clients = Client.paginate(page: params[:page], per_page:4)
  end

  def new
    @clients = Client.new
    authorize @clients
  end

  def edit

  end

  def show
  end

  def create
    @clients = Client.new(client_params)

    respond_to do |format|
      if @clients.save
        format.html {redirect_to clients_url, notice: 'Cliente creado exitosamente'}
        format.json {render :show, status: :created, location: @clients}
      else
        format.html {render :new}
        format.json {reder json: @clients.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @clients.update (client_params)
        format.html {redirect_to clients_url, notice: 'El clientes se ha actualizado exitosamente'}
        format.json {reder :show, status: :ok, location: @clients}
      else
        format.html {render :edit}
        format.json {render json: @clients.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @clients.destroy
    respond_to do |format|
      format.html {redirect_to clients_url, notice: 'Cliente eliminado con éxito'}
      format.json { head :no_content}

    end
  end

  private

  def set_client
    @clients = Client.find(params[:id])

  end

  def client_params
    params.require(:client).permit(:nombre, :correo, :direccion, :cedula, :telefono, :estado)

  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@clients) do |e| %>
  <div class="form-inputs">
    <%= e.input :nombre%>
    <%= e.input :correo%>
    <%= e.input :direccion%>
    <div class="row">
      <div class="col">
        <%= e.input :cedula%>
      </div>
      <div class="col">
        <%= e.input :telefono%>
      </div>
    </div>
    <span>¿Desea activar este cliente?</span>
    <%= e.input :estado%>
  </div>
  <div class="form-actions">
    <%= e.button :submit, class: "btn btn-primary btn-block" %>
  </div>
<%end%>

app/views/clients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <div class="card shadow">
        <div class="card-body">
          <h4 align="center"> Editar cliente</h4>
          <%= render 'form', client: @client%>
          <br>
          <%= link_to 'Show', @category %> |
          <%= link_to 'Back', client_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container-fluid p-2">
  <h1>Clientes</h1>
  <div>
    <%= link_to new_client_path, {class: "btn btn-info shadow"} do%>
    <%= fa_icon "plus-circle" %>
    Nuevo cliente
    <%end%>
  </div>
  <br>
  <div class="card shadow">
    <div class="card-body">
      <div class="table-responsive">
        <table id="TablaClients" class="table table-bordered table-hover">
          <thead>
            <tr>
             <% if @clients.empty? %>
              <th>Nombre</th>
              <th>Correo</th>
              <th>Dirección</th>
              <th>Cédula</th>
              <th>Telefono</th>
              <th>Estado</th>
             <% else %>
              <th>Nombre</th>
              <th>Correo</th>
              <th>Dirección</th>
              <th>Cédula</th>
              <th>Telefono</th>
              <th>Estado</th>
              <th colspan="3"></th>
             <% end %>
            </tr>
          </thead>
          <tbody>
            <% @clients.each do |client|%>
            <tr>
              <td><%= client.nombre %></td>
              <td><%= client.correo %></td>
              <td><%= client.direccion %></td>
              <td><%= client.cedula %></td>
              <td><%= client.telefono %></td>
              <td><%= client.estado %></td>
              <td align="center"><%= link_to 'Editar', edit_client_path(client), class:"btn btn-info" %></td>
              <td align="center"><%= link_to 'Borrar', client, method: :delete, data: { confirm: "Desea borrar el cliente #{client.nombre}?"}, class:"btn btn-danger" %></td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-2">
  <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/clients/new.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-5 mx-auto">
      <div class="card shadow">
        <div class="card-body">
          <h4 align="center"> Nuevo Cliente</h4>
          <%= render 'form', client: @client%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @clients.nombre %>
</p>

<p>
  <strong>Correo</strong>
  <%= @clients.correo%>
</p>
<p>
  <strong>Direccion</strong>
  <%= @clients.direccion%>
</p>
<p>
  <strong>Cédula</strong>
  <%= @clients.cedula%>
</p>
<p>
  <strong>Telefono</strong>
  <%= @clients.telefono%>
</p>

<%= link_to 'Edit', edit_client_path(@clients) %> |
<%= link_to 'Back', clients_path %>