config/routes.rb
Rails.application.routes.draw do
  # get 'sales/index'
  # get 'sales/new'
  # get 'clients/index'
  # get 'clients/new'
  # get 'clients/show'
  # get 'clients/edit'
  # namespace :categories do
  #   get 'dishes/index'
  #   get 'dishes/new'
  #   get 'dishes/edit'
  #   get 'dishes/show'
  # end
  # resources :dishes
  # resources :categories
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :profiles
  resources :clients
  resources :sales
  resources :categories do
    resources :dishes, module: :categories
  end
  post '/search', to: 'search#results'
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_details
  belongs_to :client
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:edit, :destroy]

  def index
    @sales = Sale.paginate(page: params[:page], per_page:4)
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_url, notice: '  se ha creado'}

        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy
      respond_to do |format|
        format.html { redirect_to sales_url, notice: 'La venta ha sido cancelada.' }
        format.json { head :no_content }
    end
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:total, :client_id)
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/index.html.erb
<div class="container-fluid">
  <h1>Registro de venta</h1>
  <div class="mb-3">
    <%= link_to new_sale_path, {class: "btn btn-info shadow"}  do %>
      <%= fa_icon "plus-circle" %>
      Nueva venta
    <%end%>
  </div>
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <% if @sales.empty? %>
                  <th>N° factura</th>
                  <th>Nombre cliente</th>
                  <th>Total</th>
                  <th>Fecha</th>
                  <% else %>
                  <th>N° factura</th>
                  <th>Nombre cliente</th>
                  <th>Total</th>
                  <th>Fecha</th>
                  <th colspan="3"></th>
                  <%end %>
                </tr>
                <tbody>
                  <% @sales.each do |sale| %>
                  <tr>
                    <td><%= sale.id %></td>
                    <td><%= sale.client.nombre %></td>
                    <td>$ <%= sale.total %></td>
                    <td><%= sale.created_at.strftime('%A, %d de %B')%></td>
                    <td align="center"><%= link_to 'Borrar', sale, method: :delete, data: {confirm: "Desea Borrar la venta"}, class: "btn btn-danger" %></td>
                    <td align="center"> <a class="btn btn-success text-light">detalles</a></td>
                  </tr>
                   <%end%>
                </tbody>
              </thead>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-2">
  <%= will_paginate @sales, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/sales/new.html.erb
<%= simple_form_for(@sale) do |f| %>
<div class="row">
  <div class="col-md-6">
    <h1 class="mb-2 text-gray">venta</h1>
  </div>
  <div class="col-md-6" style="text-align:right;">
    <h3 class="mr-3" id="total_venta_lbl">Total $  <%= @sale.total %></h3>
  </div>
  <div class="col-md-5">
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#buscador_plato">Buscar plato</button>
    <button type="button" class="btn btn-info"data-toggle="modal" data-target="#buscador_cliente">Buscar cliente</button>
  </div>
  <div class="col-md-7" style="text-align:right;">
    <%= f.button :submit, 'Generar venta', class: "btn btn-primary" %>
    <a class="btn btn-danger" href="/sales">Cancelar venta</a>
    <%# <%= redirect_to 'Cancelar Venta', sale_path ,  %>
  </div>
  <div class="col-md-3" id="cliente_venta">
   <h5 class="mt-4">Datos del cliente</h5>
   <%= f.association :client %>
  </div>
</div>
<br>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="tabla_ventas">
        <thead>
          <tr>
            <th>Plato</th>
            <th>Cantidad</th>
            <th>Precio unitario</th>
            <th>Precio total</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div
  </div>
</div>
<% @model = @sale %>
<%= render 'search/dishes', model: @model, tipo: "sale" %>
<%# render 'search/clients' %>
<% end %>